plugin: aws_ec2
regions:
  - eu-central-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags
    prefix: tag
  - key: key_name
    prefix: 3ants
compose:
  ansible_host: private_ip_address
