---
datadog_checks:
  process:
    init_config:
    instances:
      - name: docker
        search_string: ['docker', 'dockerd']
  tcp_check:
    init_config:
    instances:
      - name: shadow-api-media
        host: localhost
        port: 8001
      - name: shadow-api-pucp
        host: localhost
        port: 8002
